# Generated by Django 6.0.5 on 2026-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_code', models.CharField(default='#02c39a', max_length=7)),
                ('image', models.ImageField(upload_to='paints_catalog/')),
            ],
        ),
    ]
