# Generated by Django 6.0.5 on 2026-06-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
    ]
